// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// PLsum
PersistenceLandscapeInterface PLsum(List pl_list);
RcppExport SEXP _plt_PLsum(SEXP pl_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pl_list(pl_listSEXP);
    rcpp_result_gen = Rcpp::wrap(PLsum(pl_list));
    return rcpp_result_gen;
END_RCPP
}
// PLdiff
List PLdiff(List pl_list);
RcppExport SEXP _plt_PLdiff(SEXP pl_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pl_list(pl_listSEXP);
    rcpp_result_gen = Rcpp::wrap(PLdiff(pl_list));
    return rcpp_result_gen;
END_RCPP
}
// PLmean
PersistenceLandscapeInterface PLmean(List pl_list);
RcppExport SEXP _plt_PLmean(SEXP pl_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pl_list(pl_listSEXP);
    rcpp_result_gen = Rcpp::wrap(PLmean(pl_list));
    return rcpp_result_gen;
END_RCPP
}
// PLvar
double PLvar(List pl_list, unsigned p);
RcppExport SEXP _plt_PLvar(SEXP pl_listSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pl_list(pl_listSEXP);
    Rcpp::traits::input_parameter< unsigned >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(PLvar(pl_list, p));
    return rcpp_result_gen;
END_RCPP
}
// PLsd
double PLsd(List pl_list, unsigned p);
RcppExport SEXP _plt_PLsd(SEXP pl_listSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pl_list(pl_listSEXP);
    Rcpp::traits::input_parameter< unsigned >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(PLsd(pl_list, p));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_class_PersistenceLandscape();
RcppExport SEXP _rcpp_module_boot_Landscape();

static const R_CallMethodDef CallEntries[] = {
    {"_plt_PLsum", (DL_FUNC) &_plt_PLsum, 1},
    {"_plt_PLdiff", (DL_FUNC) &_plt_PLdiff, 1},
    {"_plt_PLmean", (DL_FUNC) &_plt_PLmean, 1},
    {"_plt_PLvar", (DL_FUNC) &_plt_PLvar, 2},
    {"_plt_PLsd", (DL_FUNC) &_plt_PLsd, 2},
    {"_rcpp_module_boot_class_PersistenceLandscape", (DL_FUNC) &_rcpp_module_boot_class_PersistenceLandscape, 0},
    {"_rcpp_module_boot_Landscape", (DL_FUNC) &_rcpp_module_boot_Landscape, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_plt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
