# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PLsum <- function(pl_list) {
    .Call(`_plt_PLsum`, pl_list)
}

PLdiff <- function(pl_list) {
    .Call(`_plt_PLdiff`, pl_list)
}

PLmean <- function(pl_list) {
    .Call(`_plt_PLmean`, pl_list)
}

PLdist <- function(pl_list, p) {
    .Call(`_plt_PLdist`, pl_list, p)
}

PLvar <- function(pl_list, p) {
    .Call(`_plt_PLvar`, pl_list, p)
}

PLsd <- function(pl_list, p) {
    .Call(`_plt_PLsd`, pl_list, p)
}

