# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PLaverage <- function(p) {
    .Call(`_plt_PLaverage`, p)
}

PLsum <- function(p1, p2) {
    .Call(`_plt_PLsum`, p1, p2)
}

PLscale <- function(scale, p) {
    .Call(`_plt_PLscale`, scale, p)
}

PLinner <- function(p1, p2) {
    .Call(`_plt_PLinner`, p1, p2)
}

PLdistance <- function(p1, p2, p) {
    .Call(`_plt_PLdistance`, p1, p2, p)
}

